# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            TheGoonies CTF blog
tagline:          'Yet another CTF blo'
description:      ''
url:              https://thegoonies.github.io
baseurl:          /

author:
  name:           'thegooniesctf'
  url:            https://twitter.com/@thegooniesctf

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/thegoonies/thegoonies.github.io
